### ISSUE TITLE
xmind-sdk-python3 dependency not being correctly installed

### ISSUE THREAD

**Issue by hduarte** [clviper/droidstatx#6]
If you don't have distribute installed or xmind-sdk-python3 already installed you will get this error.

Output:

[-]Downloading latest Apktool version...
Downloaded 16314178 of 16314178 bytes (100.00%)
Collecting androguard from git+https://github.com/androguard/androguard.git#egg=androguard (from -r requirements.txt (line 1))
  Cloning https://github.com/androguard/androguard.git to /tmp/pip-install-emslwmhw/androguard
Collecting xmind from git+https://github.com/neskk/xmind-sdk-python3.git#egg=xmind (from -r requirements.txt (line 2))
  Cloning https://github.com/neskk/xmind-sdk-python3.git to /tmp/pip-install-emslwmhw/xmind
Requirement already satisfied, skipping upgrade: asn1crypto>=0.24.0 in /usr/lib/python3/dist-packages (from androguard->-r requirements.txt (line 1)) (0.24.0)
Requirement already satisfied, skipping upgrade: click in /usr/local/lib/python3.7/dist-packages (from androguard->-r requirements.txt (line 1)) (7.0)
Requirement already satisfied, skipping upgrade: colorama in /usr/local/lib/python3.7/dist-packages (from androguard->-r requirements.txt (line 1)) (0.4.1)
Collecting ipython>=5.0.0 (from androguard->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/a9/2e/41dce4ed129057e05a555a7f9629aa2d5f81fdcd4d16568bc24b75a1d2c9/ipython-7.5.0-py3-none-any.whl (770kB)
    100% |████████████████████████████████| 778kB 2.1MB/s 
Collecting lxml (from androguard->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/66/20/49201c7bcb1c92942ac98658b09fb4a0c0dcd064d439489349bc5891207c/lxml-4.3.3-cp37-cp37m-manylinux1_x86_64.whl (5.7MB)
    100% |████████████████████████████████| 5.7MB 225kB/s 
Collecting matplotlib (from androguard->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/dc/cb/a34046e75c9a4ecaf426ae0d0eada97078c8ce4bbe3250940b1a312a1385/matplotlib-3.1.0-cp37-cp37m-manylinux1_x86_64.whl (13.1MB)
    100% |████████████████████████████████| 13.1MB 85kB/s 
Collecting networkx>=1.11 (from androguard->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/85/08/f20aef11d4c343b557e5de6b9548761811eb16e438cee3d32b1c66c8566b/networkx-2.3.zip (1.7MB)
    100% |████████████████████████████████| 1.8MB 1.1MB/s 
Collecting pydot>=1.4.1 (from androguard->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/33/d1/b1479a770f66d962f545c2101630ce1d5592d90cb4f083d38862e93d16d2/pydot-1.4.1-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: pygments in /usr/local/lib/python3.7/dist-packages (from androguard->-r requirements.txt (line 1)) (2.3.1)
Collecting distribute (from xmind->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/5f/ad/1fde06877a8d7d5c9b60eff7de2d452f639916ae1d48f0b8f97bf97e570a/distribute-0.7.3.zip (145kB)
    100% |████████████████████████████████| 153kB 7.9MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-emslwmhw/distribute/setuptools/__init__.py", line 2, in <module>
        from setuptools.extension import Extension, Library
      File "/tmp/pip-install-emslwmhw/distribute/setuptools/extension.py", line 5, in <module>
        from setuptools.dist import _get_unpatched
      File "/tmp/pip-install-emslwmhw/distribute/setuptools/dist.py", line 7, in <module>
        from setuptools.command.install import install
      File "/tmp/pip-install-emslwmhw/distribute/setuptools/command/__init__.py", line 8, in <module>
        from setuptools.command import install_scripts
      File "/tmp/pip-install-emslwmhw/distribute/setuptools/command/install_scripts.py", line 3, in <module>
        from pkg_resources import Distribution, PathMetadata, ensure_directory
      File "/tmp/pip-install-emslwmhw/distribute/pkg_resources.py", line 1518, in <module>
        register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
    AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-emslwmhw/distribute/

**Comment by clviper** [comment]
Install script adjusted to correctly install the dependencies.
