### ISSUE TITLE
Can't open the .Xmind files

### ISSUE THREAD

**Issue by G0T-R00T** [clviper/droidstatx#7]
Hi team,

Can someone please tell me why I can't open the .xmind file in XMind software anymore? I have a fresh install of droidstatx.

Thanks,

**Comment by clviper** [comment]
Hi,

What version of Xmind are you using? Xmind Zen is not compatible with this
format.

**Comment by G0T-R00T** [comment]
Life saver. I changed my install to normal Xmind and it is working now. While building my new machine I installed Xmind Zen hehe. Thanks for your help :)
